apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: movies
  template:
    metadata:
      labels:
        app.kubernetes.io/name: movies
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: movies
    spec:
      containers:
      - name: movies
        image: ghcr.io/mycodedynamic/kotlin-elastic:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
        ports:
          - containerPort: 8080
