name: Deploy kotlin app
on:
  push:
    branches:
      - master
permissions:
  contents: read
  packages: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Clear GitHub token credentials
        run: |
          git config --unset-all http.https://github.com/.extraheader || true
          git config --global --unset-all http.extraheader || true
      - name: Push clean shallow to personal repo
        run: |
          git config --global user.name 'Marian505'
          git config --global user.email 'marian.cakajda@gmail.com'
          git remote add public https://x-access-token:${{ secrets.PERSONAL_PAT }}@github.com/marian505/kotlin-elastic.git || true
          git remote set-url public https://x-access-token:${{ secrets.PERSONAL_PAT }}@github.com/marian505/kotlin-elastic.git || true
          git checkout --orphan clean-main
          git add -A
          git commit -m "Shallow sync $(date)"
          git push public clean-main:main --force
  build:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Lowercase repo repo
        run: echo "REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Lowercase repo repo
      run: echo "REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pull image from GHCR
      run: sudo ctr -n k8s.io images pull --user ${{ github.actor }}:${{ secrets.PERSONAL_PAT }} ghcr.io/${{ env.REPO }}:latest
    - name: Cleanup previous Helm release
      run: |
        helm -n dev uninstall movies --no-hooks || true
        kubectl delete pod -l app.kubernetes.io/instance=movies -n dev --force --grace-period=0 --ignore-not-found || true
    - name: Deploy Helm chart
      run: helm upgrade --install movies ./helm